### PR TITLE
UPSTREAM: <carry>: add dynamic certificate reloading

### PR DESCRIPTION
**Pull request by mfojtik**
This picks the cert reloading to fix openshift apiserver.
When this merge, we just bump the openshift-apiserver repo.

The proof with fake bump: https://github.com/openshift/openshift-apiserver/pull/16

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k @tnozicka lets bring the publishing discussion here, so we have record on how to deal with things like this...

In summary, we seems to have multiple options:

1) You make PR like this, we merge it, then you bump openshift-apiserver and you are done. If you need to CI the backport, you can add a fake bump commit to your openshift-apiserver PR.

2) You open PR against openshift/kubernetes. You change the staging/ folder there and let the bot sync the changes to this repository.

3) You open PR against openshift/kubernetes. Then if the repository vendor kubernetes, we make a symlink.

**Comment by soltysh** [comment]
> * You make PR like this, we merge it, then you bump openshift-apiserver and you are done. If you need to CI the backport, you can add a fake bump commit to your openshift-apiserver PR.

This will make rebase hard, b/c you'll have to look for commits across several repos. As long as k8s keeps staging withing single k8s repo we should follow, only when repos will be split we can take this approach.

> * You open PR against openshift/kubernetes. You change the staging/ folder there and let the bot sync the changes to this repository.

:+1: always single source of truth to follow the exact pattern upstream use.

> * You open PR against openshift/kubernetes. Then if the repository vendor kubernetes, we make a symlink.

This is a combination of a previous one, which makes sense only for those repos which have all of k/k, others should use only the necessary bits, imo.

**Comment by mfojtik** [comment]
> This will make rebase hard, b/c you'll have to look for commits across several repos. As long as k8s keeps staging withing single k8s repo we should follow, only when repos will be split we can take this approach.

Let say kubernetes move away from staging in long run. Also kubernetes publish the staging to external repos today, so we don't have to rely on `staging/` in kubernetes/kubernetes anymore right? We can just bump each repo individually and apply the carries on each repository.

**Comment by tnozicka** [comment]
I think we should use 2. and 3. depending is you already vendor kubernetes fork. if you do we symlink (avoids skews), if not vendor published branch.

I agree we should keep caries and backport in one place, also bacport will be easier to apply in the repo (kubernetes) where they were initially committed

**Comment by soltysh** [comment]
In general, I'd follow upstream with where we apply patches, if they split, we'll split too, that's the simplest approach.

**Comment by tnozicka** [comment]
> Let say kubernetes move away from staging in long run. Also kubernetes publish the staging to external repos today, so we don't have to rely on staging/ in kubernetes/kubernetes anymore right? 

except skews

We can just bump each repo individually and apply the carries on each repository.

At this point the backport can include multiple staging repos. If not it's just easier but I don't see it happening anytime soon

**Comment by mfojtik** [comment]
> except skews

What you mean?

> We can just bump each repo individually and apply the carries on each repository.

Why not? You would think it will be too much work? Or is there some other reason?

> At this point the backport can include multiple staging repos. If not it's just easier but I don't see it happening anytime soon

Sure, you can always apply the backport to openshift/kubernetes (some branch), let the bot synchronize it to forks and then just bump? I think that is solvable problem.

**Comment by mfojtik** [comment]
@tnozicka @soltysh I think for now, I would just button merge this when the fake bump (https://github.com/openshift/openshift-apiserver/pull/16) is green and @stlaz will verify this fix
the BZ. Then I will open a real bump in openshift-apiserver that we can tag and merge via bot.

@deads2k I think that is the process we agreed on before I went to PTO ;-)

**Comment by tnozicka** [comment]
> >except skews
>What you mean?

kubernetes commits are atomic for all the repos in staging if bot breaks on some of them or is just slow you get levels of kube stuff that was never tested or meant to work together

> Why not? You would think it will be too much work? Or is there some other reason?

Given the same reasons and because a commit can transcend staging repos - you would have split a patch that might e.g. needed the other repo it includes patched as well.

> Sure, you can always apply the backport to openshift/kubernetes (some branch), let the bot synchronize it to forks and then just bump? I think that is solvable problem.

That is hard to determine and has the skew problem described above

**Comment by tnozicka** [comment]
also technically, for glide dep resolution, we need publishing for vendoring k8s.io/kubernetes to work correctly, although we overwrite those published deps with symlinks. That's what we do in origin - it depends on published repos and then overwrites with symlinks to avoid skew

**Comment by mfojtik** [comment]
I'm going to follow what @deads2k did already for openshift-apiserver repo. Merging this PR with button per @stlaz LGTM and bumping the openshift-apiserver to pick this up.

**Comment by deads2k** [comment]
Given the state of golang vendoring, upstream goals, and desired separation, our energy should be spent trying to eliminate k/k dependencies.  The rebase is actually pretty easy to perform because the dep tree is comparatively shallow and complements the tools instead of fighting them.  Dependencies on staging makes pulling new levels become a multistage process involving at least two bots.

Look at oc as an example, the k/k dep must be eliminated or you risk being unable to find matching levels.  OAS as an example reveals dependencies which aren't intended as stable.

Updating repos in order for o(10) patches is so comparatively easy, I don't think the trade-off for multiple bots which require three stage updates to work and fight with vendoring and go mod can be justified.  I'm so convinced that I'm taking the time to write this now and I can explain the flows in more detail on Monday.

Don't us "it's hard to vendor k/k" as reason to pull this backwards.

**Pull request merged**
