### PR TITLE
Rebase 1.31

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Cherry-pick carry patches to 4.18/1.31

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@p0lyn0mial @tkashem PTAL

**Comment by p0lyn0mial** [comment]
@dinhxuanvu did you run into any issues when merging the patches?

@dinhxuanvu I see that some e2e tests for openshift-apiserver failed. Are these failures related to changes in this PR?

**Comment by dinhxuanvu** [comment]
> @dinhxuanvu did you run into any issues when merging the patches?
> 
> @dinhxuanvu I see that some e2e tests for openshift-apiserver failed. Are these failures related to changes in this PR?

No issues during cherry-picking patches for KAS. There are some issues with unit tests on OAS but I'm fixing them up right now. Just upstream changes. No major issues so far.

**Comment by p0lyn0mial** [comment]
> There are some issues with unit tests on OAS but I'm fixing them up right now

mhm, I think that all e2e jobs failed. I checked https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_openshift-apiserver/458/pull-ci-openshift-openshift-apiserver-master-e2e-aws-ovn/1853871937520930816/artifacts/e2e-aws-ovn/gather-extra/artifacts/pods/openshift-apiserver_apiserver-65bf844bcb-rm9sj_openshift-apiserver.log

and it looks like that OAS didn't start due to:
```
cmd.go:74] failed to initialize admission plugin "ResourceQuota": missing quotaConfiguration
```

I think we should ensure at least some e2e tests pass to confirm that the changes in this PR are correct and no further changes are needed before merging. WDYT?

**Comment by dinhxuanvu** [comment]
> I think we should ensure at least some e2e tests pass to confirm that the changes in this PR are correct and no further changes are needed before merging. WDYT?

I pushed some changes. I expect unit tests to pass now and we can see some clear signals on e2e. Let see if we bump into any issues. When CI is green on OAS, we can merge KAS.

**Comment by tkashem** [comment]
the proof pr is green

/lgtm
/approve

**Comment by dinhxuanvu** [comment]
@p0lyn0mial Ready for merge.

**Pull request merged**
