### PR TITLE
API-1820: Add carry patches from 4.16 to 4.17 for k8s 1.30 rebase

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Carry patches from 4.16 over to 4.17 (1.30.3)

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
Proof PR: https://github.com/openshift/openshift-apiserver/pull/441

**Comment by dinhxuanvu** [comment]
@soltysh PTAL

**Comment by chiragkyal** [comment]
Are we good bumping to `1.30.3` whereas other repos are at `1.30.1`?

**Comment by dinhxuanvu** [comment]
> Are we good bumping to `1.30.3` whereas other repos are at `1.30.1`?

All patch versions should be compatible so you should be fine.

**Comment by chiragkyal** [comment]
>All patch versions should be compatible so you should be fine.

So, if I bump library-go which is at `1.30.1` into `openshift-apiserver`, is it safe to assume the kube version will be untouched?

**Comment by dinhxuanvu** [comment]
> > All patch versions should be compatible so you should be fine.
> 
> So, if I bump library-go which is at `1.30.1` into `openshift-apiserver`, is it safe to assume the kube version will be untouched?

I expect so.

**Comment by p0lyn0mial** [comment]
@dinhxuanvu I think some patches have been added to the 4.16 branch since you opened this one.

**Comment by dinhxuanvu** [comment]
@p0lyn0mial The 1.30-bump PR passed CI on openshift-apiserver except for build job which seems unrelated given the fact it also fails on master. Can we go ahead and merge this PR so I can update the OAS PR? Thanks.

**Comment by tkashem** [comment]
/lgtm
/approve

/hold
(if you want @p0lyn0mial to review, otherwise feel free to cancel it)

**Pull request merged**
