### PR TITLE
NO-ISSUE: UPSTREAM: 118886: KEP-1040: Deep disablement for APF based on --enable-priority-and-fairness.

### PR DESCRIPTION
**Pull request by p0lyn0mial**
pulls https://github.com/kubernetes/kubernetes/pull/118886 

which will allow for disabling the apf by passing a command line flag.

the proof PR for oauth-apiserver https://github.com/openshift/oauth-apiserver/pull/106
the proof PR for openshift-apiserver https://github.com/openshift/openshift-apiserver/pull/418

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

I'd like to verify it first.

**Comment by tkashem** [comment]
yes, APF should be disabled in an aggregated apiserver

/lgtm

**Comment by p0lyn0mial** [comment]
/assign @deads2k 

for approval

**Pull request merged**
