### PR TITLE
UPSTREAM: <carry>: temporary hack to prevent repeated registration of the start-apiserver-admission-initializer

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
should unblock https://github.com/openshift/openshift-apiserver/pull/441

**Comment by dinhxuanvu** [comment]
I added your commit into my pending rebase PR: #57

**Comment by p0lyn0mial** [comment]
/close

I prefer https://github.com/openshift/openshift-apiserver/pull/452

**Pull request closed without merging**
