### PR TITLE
NO-JIRA: UPSTREAM: <carry>: retrying etcd Unavailable errors for the etcd health and ready checkers

### PR DESCRIPTION
**Pull request by p0lyn0mial**
clean pick, compare with https://github.com/openshift/kubernetes/pull/2079

proof PRs look good:
- https://github.com/openshift/openshift-apiserver/pull/447
- https://github.com/openshift/oauth-apiserver/pull/119

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold 

for a proof pr

**Comment by p0lyn0mial** [comment]
proof PRs:
- https://github.com/openshift/openshift-apiserver/pull/447
- https://github.com/openshift/oauth-apiserver/pull/119

**Comment by deads2k** [comment]
get an lgtm from someone on the apiserver team

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
